### ISSUE TITLE
Repeated crash in garden after using Sprayonator with Tasty Cheese

### ISSUE THREAD

**Issue by timothyreavis** [hannibal00212/SkyHanni#1163]
Unsure if the crash is related to the Sprayonator, but it began occurring right after using it for the first time.

Using Version 0.23 on Modrinth.

`[11:39:35] [Client thread/FATAL]:
 Unreported exception thrown!
java.lang.IllegalArgumentException: Char ? is not a decimal digit
	at kotlin.text.CharsKt__CharKt.digitToInt(Char.kt:24) ~[Essential%20(forge_1.8.9).jar:?]
	at at.hannibal2.skyhanni.mixins.hooks.GuiIngameHookKt.replaceString(GuiIngameHook.kt:38) ~[GuiIngameHookKt.class:?]
	at at.hannibal2.skyhanni.mixins.hooks.GuiIngameHookKt.drawString(GuiIngameHook.kt:18) ~[GuiIngameHookKt.class:?]
	at net.minecraft.client.gui.GuiIngame.redirect$zbk000$renderItemOverlayPost(GuiIngame.java:4291) ~[avo.class:?]
	at net.minecraft.client.gui.GuiIngame.renderScoreboard(GuiIngame.java:611) ~[avo.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:165) ~[GuiIngameForge.class:?]
	at club.sk1er.patcher.screen.render.caching.HUDCaching.renderCachedHud(HUDCaching.java:48) ~[HUDCaching.class:?]
	at net.minecraft.client.renderer.EntityRenderer.redirect$zmn000$patcher$renderCachedHUD(EntityRenderer.java:10558) ~[bfk.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1401) ~[bfk.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1051) ~[ave.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:173) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:117) [stage2.forge_1.8.9.jar:?]
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:147) [stage2.forge_1.8.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293) [stage1.jar:7]
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44) [stage1.jar:7]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_382]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_382]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_382]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_382]
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53) [ctjs-2.2.0-1.8.9.jar:?]
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26) [ctjs-2.2.0-1.8.9.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.8.0_382]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [?:1.8.0_382]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_382]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_382]
	at java.lang.Class.newInstance(Class.java:442) [?:1.8.0_382]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`

**Comment by martimavocado** [comment]
disable "plot name in scoreboard" for now, please have future bug reports in discord

**Comment by lunaynx** [comment]
Known issue, should be fixed in the latest beta. Alternatively, you can turn off "Plot Name In Scoreboard" to fix the crash.

For future reference, it's preferred to report bugs on the Discord server.

**Comment by timothyreavis** [comment]
I cannot enter my wheat field sprayed with tasty cheese unless SkyHanni is disabled. Once SkyHanni is disabled, my client no longer crashes.

**Comment by timothyreavis** [comment]
Thank you
