### ISSUE TITLE
Enderman Slayer Damage Indicator Hit display

### ISSUE THREAD

**Issue by hannibal002** [hannibal00212/SkyHanni#159]
```
java.lang.NumberFormatException: For input string: "? 96"
[19:27:10] [Client thread/INFO]: [at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager:checkEntity:362]: 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[19:27:10] [Client thread/INFO]: [at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager:checkEntity:362]: 	at java.lang.Integer.parseInt(Integer.java:580)
[19:27:10] [Client thread/INFO]: [at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager:checkEntity:362]: 	at java.lang.Integer.parseInt(Integer.java:615)
[19:27:10] [Client thread/INFO]: [at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager:checkEntity:362]: 	at at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager.checkEnderSlayer(DamageIndicatorManager.kt:622)
[19:27:10] [Client thread/INFO]: [at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager:checkEntity:362]: 	at at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager.getCustomHealth(DamageIndicatorManager.kt:381)
[19:27:10] [Client thread/INFO]: [at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager:checkEntity:362]: 	at at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager.checkEntity(DamageIndicatorManager.kt:339)
[19:27:10] [Client thread/INFO]: [at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager:checkEntity:362]: 	at at.hannibal2.skyhanni.features.damageindicator.DamageIndicatorManager.onTick(DamageIndicatorManager.kt:306)
```

**Comment by hannibal002** [comment]
@jani270

**Comment by jani270** [comment]
> @jani270

?
