### ISSUE TITLE
The game crashes when I try to use the mod

### ISSUE THREAD

**Issue by Halnest** [hannibal00212/SkyHanni#344]
the game loads until it's 7/7 with all the mods then it crashes saying this: Error: java.lang.NoClassDefFoundError: kotlin/collections/MapsKt

the report says this:

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/29/23 9:16 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: kotlin/collections/MapsKt
	at at.hannibal2.skyhanni.data.GuiEditManager.<clinit>(GuiEditManager.kt:54)
	at net.minecraft.client.renderer.EntityRenderer.handler$onLastRender$zdc000(EntityRenderer.java:3559)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1482)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: kotlin.collections.MapsKt
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 340299168 bytes (324 MB) / 1546649600 bytes (1475 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_M5 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	devjg_fullbright{2.3.0} [Fullbright] (FullBright-2.3.0.jar) 
	UCHIJA	notenoughupdates{2.1.0-REL} [NotEnoughUpdates] (NotEnoughUpdates-2.1.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 387.92' Renderer: 'GeForce GT 730/PCIe/SSE2'
	Launched Version: forge-11.15.1.2318

**Comment by superhize** [comment]
Hello, please use patcher https://static.sk1er.club/repo/mods/patcher/1.8.7/1.8.9/Patcher-1.8.7%20(1.8.9).jar

**Comment by superhize** [comment]
Hello again, please use the latest beta (0.19 Beta 18) to fix that, you don't need patcher anymore. 
https://github.com/hannibal002/SkyHanni/releases
