### ISSUE TITLE
SkyHanni 0.20.Beta.13: Unknown dicer: POTATO

### ISSUE THREAD

**Issue by brandonwamboldt** [hannibal00212/SkyHanni#432]
Sorry if this has already been reported, i looked and didnt see any issues referencing it. I get this error with a level 2 potato hoe, havent narrowed down what causes it exactly, seems to be after melon farming though. 

```
SkyHanni 0.20.Beta.13: Unknown dicer: POTATO
 
Caused by kotlin.collections.builders.ListBuilder: Unknown dicer: POTATO
	at SH.test.command.CopyErrorCommand.skyHanniError(CopyErrorCommand.kt:20)
	at SH.features.garden.farming.CropMoneyDisplay.drawDisplay(CropMoneyDisplay.kt:141)
	at SH.features.garden.farming.CropMoneyDisplay.update(CropMoneyDisplay.kt:85)
	at SH.features.garden.farming.CropMoneyDisplay.onTick(CropMoneyDisplay.kt:79)
	at SH.events.LorenzEvent.postAndCatch(LorenzEvent.kt:15)
	at SH.data.MinecraftData.onTick(MinecraftData.kt:68)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2151)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at gg.essential.loader.stage2.relaunch.Relaunch.relaunch(Relaunch.java:124)
	at gg.essential.loader.stage2.EssentialLoader.preloadEssential(EssentialLoader.java:173)
	at gg.essential.loader.stage2.EssentialLoader.loadPlatform(EssentialLoader.java:117)
	at gg.essential.loader.stage2.EssentialLoaderBase.load(EssentialLoaderBase.java:147)
	at gg.essential.loader.stage1.EssentialLoaderBase.load(EssentialLoaderBase.java:293)
	at gg.essential.loader.stage1.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:44)
	at gg.essential.loader.stage0.EssentialSetupTweaker.loadStage1(EssentialSetupTweaker.java:53)
	at gg.essential.loader.stage0.EssentialSetupTweaker.<init>(EssentialSetupTweaker.java:26)
	at java.lang.Class.newInstance(Class.java:442)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Potato hoe:

```
{
    id: "minecraft:iron_hoe",
    Count: 1b,
    tag: {
        ench: [],
        Unbreakable: 1b,
        HideFlags: 254,
        display: {
            Lore: ["§7Speed: §a+9 §9(+9)", "§7Farming Fortune: §a+71.5 §9(+9)", "§7Farming Wisdom: §a+3 §9(+3)", "", "§9Harvesting V", "§7Grants §a+62.5 §6☘ Farming", "§6Fortune§7, which increases your", "§7chance for multiple crops.", "§9Replenish I", "§7Upon breaking crops, nether", "§7wart, or cocoa, automatically", "§7replant from materials in your", "§7inventory.", "§9Turbo-Potato IV", "§7Grants §a+20 §6☘ Farming Fortune", "§6§7when breaking potato§7.", "§7Requires §cBronze §7in §aPotato §7contest!", "", "§7Gain §6+25☘ Farming Fortune", "§6§7and §3+3☯ Farming Wisdom §7for", "§7potatoes.", "", "§7Counter: §e6,690,728 Potatoes", "", "§6Logarithmic Counter", "§7Gain §6+16☘ Farming Fortune", "§6§7for potatoes per digits on the", "§7Counter, minus 4!", "§7You have §6+48☘ Farming Fortune", "§6§7for potatoes.", "", "§7§8Bonus potatoes percent", "§8increases your Farmhand perk's", "§8chances", "", "§eReach 10M Counter for +1 Rarity!", "§eRight-click to view recipes!", "", "§9Blessed Bonus", "§7Grants §6+9☘ Farming Fortune", "§6§7and §3+3☯ Farming Wisdom§7.", "", "§8§l* §8Co-op Soulbound §8§l*", "§9§lRARE HOE"],
            Name: "§9Blessed Pythagorean Potato Hoe"
        },
        ExtraAttributes: {
            mined_crops: 6690801L,
            modifier: "blessed",
            id: "THEORETICAL_HOE_POTATO_2",
            enchantments: {
                harvesting: 5,
                turbo_potato: 4,
                replenish: 1
            },
            uuid: "e02ca62c-f515-4235-b4a0-5e31fec96c90",
            donated_museum: 1b,
            timestamp: "6/30/23 12:14 PM"
        }
    },
    Damage: 0s
}
```

**Comment by hannibal002** [comment]
Thank you for the report and the extra data!
Is there any chance you have renamed one farming tool to "potato dicer" or something similar with NEU's “/item rename” feature?
Or were you farming potatoes with a melon dicer?


Furthermore, for the future, please consider using the discord for bug reports instead of the GitHub issue pages.

**Comment by brandonwamboldt** [comment]
I did not use the rename feature, but perhaps i hit a potato with the melon dicer of a melon with the potato hoe, i'll do some more testing to see if i can reproduce the issue. And noted about discord, my mistake!
